# @name post_produto
POST http://127.0.0.1:5000/produtos
Content-Type: application/json


{
    "nome": "Banana",
    "qtd_estoque": 10,
    "preco": 10.50
}

###

# @name get_produto
GET http://127.0.0.1:5000/produtos/16eb4115-eb84-4d25-affe-832f235d67cd


###

# @name get_produtos
GET http://127.0.0.1:5000/produtos


###

# @name put_produto
PUT http://127.0.0.1:5000/produtos/5ce2873c-4b52-4dc9-a038-9416fad2bc28
Content-Type: application/json

{
    "nome": "Macarrão",
    "qtd_estoque": 11,
    "preco": 10.50
}

###

# @name delete_produto
DELETE http://127.0.0.1:5000/produtos/16eb4115-eb84-4d25-affe-832f235d67cd
