# @name get_cursos
GET http://localhost:5000/cursos


### 

# @name post_curso
POST http://localhost:5000/cursos
Content-Type: application/json

{
    "nome": "Curso de django",
    "descricao": "Curso top de django",
    "data_publicacao": "2021-09-01"
}