"""criando migração

Revision ID: 86c86e186a3a
Revises: 
Create Date: 2024-11-13 15:06:09.783598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c86e186a3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apelido', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_column('apelido')

    # ### end Alembic commands ###
