"""empty message

Revision ID: d2253c625455
Revises: 2544e3bd657f
Create Date: 2024-11-14 11:13:51.565014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2253c625455'
down_revision = '2544e3bd657f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_column('apelido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apelido', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
